### ISSUE TITLE
The site setup seems to be outdated and can't install properly anymore 

### ISSUE THREAD

**Issue by Viktor286** [json-api/explorer#49]
The site setup seems to be outdated and can't be install properly anymore.
There is a lot of deprecated and no longer supported packages used.

In my specific case, i get fatal error on installation step, probably related to the fact that i have [volta](https://volta.sh/) installed globally.

```
npm WARN deprecated core-js@2.6.9: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /Users/user/dev/explorer/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /Users/user/.volta/tools/image/node/18.20.2/bin/node /Users/user/dev/explorer/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/Users/user/.volta/tools/image/node/18.20.2/bin/node',
npm ERR! gyp verb cli   '/Users/user/dev/explorer/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.20.2 | darwin | arm64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/user/dev/explorer/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/user/dev/explorer/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/user/dev/explorer/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/user/dev/explorer/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/user/dev/explorer/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/user/dev/explorer/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/user/dev/explorer/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/user/dev/explorer/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/user/dev/explorer/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/user/dev/explorer/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/user/dev/explorer/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/user/dev/explorer/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/user/dev/explorer/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/user/dev/explorer/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/user/dev/explorer/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/user/dev/explorer/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/user/dev/explorer/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/user/dev/explorer/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/user/dev/explorer/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/user/dev/explorer/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/user/dev/explorer/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/user/dev/explorer/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/user/dev/explorer/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/user/dev/explorer/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/Users/user/dev/explorer/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/Users/user/dev/explorer/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/Users/user/dev/explorer/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/Users/user/dev/explorer/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /Users/user/dev/explorer/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /Users/user/dev/explorer/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /Users/user/dev/explorer/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:202:21)
npm ERR! gyp ERR! System Darwin 23.4.0
npm ERR! gyp ERR! command "/Users/user/.volta/tools/image/node/18.20.2/bin/node" "/Users/user/dev/explorer/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /Users/user/dev/explorer/node_modules/node-sass
npm ERR! gyp ERR! node -v v18.20.2
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1
```

**Comment by bradjones1** [comment]
I think this package is unmaintained.
